### ISSUE TITLE
An error has occurred. Check your logs or contact the app author for clarification.

### ISSUE THREAD

**Issue by Canderson156** [UP-macroecology/ODMAP#7]
Hi there,

I've been using your shiny app for the last few weeks. It's super awesome and helpful. But it hasn't been working last since last Friday. The page does not load, instead showing: 

An error has occurred!

An error has occurred. Check your logs or contact the app author for clarification.

Could you provide any clarification on when you expect this issue to be resolved? Thanks very much.

**Comment by JetteReeg** [comment]
Hi, 

thanks for reporting the error. I just checked the Shiny App locally on my Windows machine and was able to run it. So I guess it is a problem with the server. I will try to fix the issue as soon as possible. Until then, you could start the app locally by downloading the repository (either using git clone, or downloading and unzipping the .zip file), open the server.R file with R Studio and clicking on 'Run App' (top right).

Best, Jette

**Comment by Canderson156** [comment]
All working now, thanks!
