### ISSUE TITLE
ODMAP website disconnects after uploading rangeModelMetaData CSV file

### ISSUE THREAD

**Issue by DylanCarbone** [UP-macroecology/ODMAP#8]
Hi Damaris and Christian,

I hope you are both well,

First of all, apologies for posting this issue initially on the wrong repo!

I would like to explore ODMAP and it's transferability with rangeModelMetaData. I've just tried to import a CSV file generated from the RMM vignette (found at https://cran.r-project.org/web/packages/rangeModelMetadata/vignettes/rmm_vignette.html) but when I attempt to upload the demo_rmmToCSV.csv file, the website disconnects. Why does this happen? Any help would be appreciated.

Thanks for your time,

Dylan

**Comment by JetteReeg** [comment]
Hi Dylan,

thanks for opening this issue. 
I have just checked the app on the website as well as locally. 
There seem to be two issues: 
First, there are some issues related to the hosting of the Shiny App on the website. (There are errors when creating a protocol from scratch and disconnects even if I try to import one of the given examples.) These issues do not occur when I run the app locally. 
Second, even if I run the app locally, I still was not able to import the RMM example. 
I will try to fix the error as soon as possible but probably only by next week. I will keep you updated.

Best,
Jette

**Comment by JetteReeg** [comment]
Hi Dylan, 
I have updated the repository and was hopefully able to fix the bug related to importing RMM files. I have included an error message, that only files with entries can be uploaded. 
You should be able to use the App now locally. Due to vacation/conference time it might take a few more days until the new app version is published online. I will let you know, when the new version is up.
Let me know if the bugfix solved you issue (either now running the app locally or later when the new version is online. 
Best,
Jette

**Comment by DylanCarbone** [comment]
Hi Jette,

I hope you are well,

Thank you so much for your help and apologies for the delay in my response, I had upcoming project deadlines I was focused on.

Unfortunately, I'm still encountering a similar issue. The app crashes when updated and ran locally, I receive:

> "Error in strsplit: non-character argument"

I've attached the file generated from the RangeModelMetaData vignette below, if that is of any help to you.


[demo_rmmToCSV.csv](https://github.com/UP-macroecology/ODMAP/files/12546898/demo_rmmToCSV.csv)

Thanks,

Dylan

**Comment by JetteReeg** [comment]
Hi Dylan, 
sorry for the delayed response. I now had another look at the ODMAP app and fixed another bug, so your test file was able to be imported without error messages. (I already pushed the fixes to the repo)
However, while digging deeper into the transfer of the rmm data into ODMAP I realized that not all sections of the rmm file are translated into the ODMAP equivalent. I need to discuss this with the ODMAP team and would like to fix this issue before updating the whole website. 
Until then, I would really appreciate it  if you could pull the updates to your local clone (or clone the repo another time) and test it another time. Please let me know if you encounter another issue!
Best, 
Jette

**Comment by DylanCarbone** [comment]
Hi Jette, 

I hope you are well,

I'm sorry for my slow responses. Thanks so much for all your help. To confirm, the RMM file upload ran successfully after your recent changes. Since opening the issue, we decided to use only ODMAP, and so we do not the RMMS-ODMAP transferability, but thanks again for fixing these issues and maintaining this brilliant app.

Thanks,

Dylan
