### ISSUE TITLE
Is the app down? 

### ISSUE THREAD

**Issue by lemus100** [UP-macroecology/ODMAP#9]
Hello there, hope all of you are doing well, 
I would like to know if the app is not working or if it has something to do with me, I'm trying to enter, but it seems to be down, I only see a blank page in the "create protocol section". Thank you for your attention, best regards.  
![image](https://github.com/UP-macroecology/ODMAP/assets/61243617/ff3d454c-d080-47f7-b604-fbc8eff092be)

**Comment by JetteReeg** [comment]
Hi,
indeed, the website seem not to work properly. 
I am currently working on fixing another bug (see issue #8) and will update the website afterwards. Until then I would kindly ask you to download the repository and run the shiny app locally in RStudio if you want to create a new protocol.
I will let you know as soon as the website is up again.
Best, Jette
